### PR TITLE
Render stomps as black dots

### PR DESCRIPTION
**Pull request by ShoshinNikita**

### CODE REVIEW

**Comment by ShoshinNikita** [comment]
Should we render deformed trees as red dots? Or maybe use a new color - for example, yellow?

**Comment by Gregory108** [comment]
@umonkey build fails, supposedly, because I initiated the merge without some sort of rights

**Comment by umonkey** [comment]
> Should we render deformed trees as red dots? Or maybe use a new color - for example, yellow?

@ShoshinNikita I would prefer yellow for all non-perfect trees, sick or deformed.

> the [build](https://github.com/umonkey/treemap/actions/runs/10442559763) fails, supposedly, because I initiated the merge without some sort of rights

@Gregory108 there was a problem with the expired login token.  Fixed in this commit, should not be a problem anymore:

https://github.com/umonkey/treemap/commit/a176a9eb739f324e44f7c551de2b138d6e44a242

**Comment by ShoshinNikita** [comment]
> I would prefer yellow for all non-perfect trees, sick or deformed.

@umonkey Maybe we can keep the color of the sick trees? If I understand correctly, the deformed trees were damaged/excessively trimmed at some point in the past, but they are healthy now. So, we can use a more neutral color - yellow in our case. However, sick trees require ±immediate attention. Therefore it's better to highlight them - keep red color.

**Comment by umonkey** [comment]
OK, I agree. I think we should split sick and deformed from the status field at some point, make them additional flags, but for now, let's do as you suggest.

**Pull request merged**
